In [1]:
##Install packages first, if you forget look up "How to install packages in spyder/python"
##Most packages should already be installed
##Manually, -m pip install [Package]
import numpy as np
import pandas as pd
import os as os

In [2]:
os.getcwd() ##Get your working directory

'C:\\Users\\Nate'

In [3]:
#Making a matrix, garbage compared to Dataframes but might be useful in the future.
hf = np.array([(1,2,3,4),(5,6,7,8)],)
print(hf)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print(hf[0])

[1 2 3 4]


In [5]:
print(hf[0,1])

2


In [6]:
#Making a series(column)
data = pd.Series([1, np.nan, 'hello', None])
print(data)

0        1
1      NaN
2    hello
3     None
dtype: object


In [7]:
k1 = pd.DataFrame({"Nate" : [1,5,6,7], "Barrett" : [4,2,3,1]}, index=["h","e","l","p"])
print(k1)
print(k1["Nate"])
print(k1["Nate"][0])

   Nate  Barrett
h     1        4
e     5        2
l     6        3
p     7        1
h    1
e    5
l    6
p    7
Name: Nate, dtype: int64
1


In [8]:
#Reading in Data
##Other ways such as using module "csv" but this is standard
Cars = pd.read_csv("cars04.csv")
Cars.head()

Vehicle Name  Hybrid  SuggestedRetailPrice  DealerCost  \
0           Chevrolet Aveo 4dr       0                 11690       10965   
1  Chevrolet Aveo LS 4dr hatch       0                 12585       11802   
2       Chevrolet Cavalier 2dr       0                 14610       13697   
3       Chevrolet Cavalier 4dr       0                 14810       13884   
4    Chevrolet Cavalier LS 2dr       0                 16385       15357   

   EngineSize  Cylinders  Horsepower  CityMPG  HighwayMPG  Weight  WheelBase  \
0         1.6          4         103       28          34    2370         98   
1         1.6          4         103       28          34    2348         98   
2         2.2          4         140       26          37    2617        104   
3         2.2          4         140       26          37    2676        104   
4         2.2          4         140       26          37    2617        104   

   Length  Width  
0     167     66  
1     153     66  
2     183     69  
3     183     68  
4     183     69

In [9]:
#JSON Data
##JSON (short for JavaScript Object Notation) has become one of the standard formats for sending data by HTTP request between web browsers and other applications. It is a much more flexible data format than a tabular text form like CSV. Here is an example:
##JSON takes the form of a dictionary
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
 {"name": "Katie", "age": 33, "pet": "Cisco"}]
}
"""

In [10]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 25, 'pet': 'Zuko'},
  {'name': 'Katie', 'age': 33, 'pet': 'Cisco'}]}

In [11]:
#jsondata =  pd.DataFrame(result)
#jsondata
#Why doesn't this work?

siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

name  age
0  Scott   25
1  Katie   33

In [12]:
#Requests
#Many websites have public APIs providing data feeds via JSON or some other format. There are a number of ways to access these APIs from Python; one easy-to-use method that I recommend is the requests package (http://docs.python-requests.org). To search for the words “python pandas” on Twitter, we can make an HTTP GET request like so:
#Let's see what nutty shit Nate did this summer.
import requests
url = "https://api.binance.com/api/v1/klines?symbol=BTCUSDT&interval=1m"
resp= requests.get(url)
rawd = resp.json()
rawd[0]

[1572358320000,
 '9319.80000000',
 '9325.02000000',
 '9315.94000000',
 '9315.94000000',
 '47.23884600',
 1572358379999,
 '440341.95747015',
 458,
 '18.71649700',
 '174470.79870716',
 '0']

In [13]:
#BeautifulSoup
from bs4 import BeautifulSoup
page = requests.get("http://dataquestio.github.io/web-scraping-pages/ids_and_classes.html")
soup = BeautifulSoup(page.content, 'html.parser')
soup

##lets,see a real world example using inspect (Google DevTools)

<html>
<head>
<title>A simple example page</title>
</head>
<body>
<div>
<p class="inner-text first-item" id="first">
                First paragraph.
            </p>
<p class="inner-text">
                Second paragraph.
            </p>
</div>
<p class="outer-text first-item" id="second">
<b>
                First outer paragraph.
            </b>
</p>
<p class="outer-text">
<b>
                Second outer paragraph.
            </b>
</p>
</body>
</html>

In [14]:
#Find by tag
soup.find('p')
soup.find_all('p')

[<p class="inner-text first-item" id="first">
                 First paragraph.
             </p>, <p class="inner-text">
                 Second paragraph.
             </p>, <p class="outer-text first-item" id="second">
 <b>
                 First outer paragraph.
             </b>
 </p>, <p class="outer-text">
 <b>
                 Second outer paragraph.
             </b>
 </p>]

In [15]:
#Find by Class (Indirect)
soup.find(class_="outer-text") 
soup.find_all(class_="outer-text")

[<p class="outer-text first-item" id="second">
 <b>
                 First outer paragraph.
             </b>
 </p>, <p class="outer-text">
 <b>
                 Second outer paragraph.
             </b>
 </p>]

In [16]:
#find by ID
soup.find(id="second")

<p class="outer-text first-item" id="second">
<b>
                First outer paragraph.
            </b>
</p>

In [17]:
#Find by both tag and class [Usual find method] [attrs = attributes(can be multiple)]
soup.find('p', attrs = {'class' : "outer-text"})

<p class="outer-text first-item" id="second">
<b>
                First outer paragraph.
            </b>
</p>

In [18]:
#To get text of the found portion
soup.find_all('p')[0].get_text()

#If the specified tag is null, get_text will throw an error

'\n                First paragraph.\n            '